In [ ]:
import pandas as pd
import numpy as np
import spacy 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('/home/intellect-1001/Desktop/Data_Scientist-/DL/DAY16/Fake_Real_Data.csv')
print(df.shape)
df.head()

(9900, 2)

                                                Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [3]:
df['label'].value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [4]:
df['label_num'] = df['label'].map({'Fake': 0,'Real': 1})
df.head()

                                                Text label  label_num
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1  U.S. conservative leader optimistic of common ...  Real          1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4  Democrats say Trump agrees to work on immigrat...  Real          1

In [5]:
nlp = spacy.load('en_core_web_lg')

In [6]:
df['vector'] = df['Text'].apply(lambda text: nlp(text).vector)
df.head()

,Text,label,label_num,vector
0,Top Trump Surrogate BRUTALLY Stabs Him In The...,Fake,0,"[-0.103623025, 0.17802684, -0.11873861, -0.034..."
1,U.S. conservative leader optimistic of common ...,Real,1,"[-0.0063406364, 0.16712041, -0.06661373, 0.017..."
2,"Trump proposes U.S. tax overhaul, stirs concer...",Real,1,"[-0.122753024, 0.17192385, -0.024732638, -0.06..."
3,Court Forces Ohio To Allow Millions Of Illega...,Fake,0,"[-0.027337318, 0.12501417, -0.0073965387, -0.0..."
4,Democrats say Trump agrees to work on immigrat...,Real,1,"[-0.032708026, 0.093958504, -0.03287002, -0.00..."

In [7]:
x = list(df['vector'])
y = df['label_num']

In [8]:
X_train, X_test, y_train, y_test = train_test_split( x, y,test_size=0.2,random_state=42)

In [9]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
nb_model = MultinomialNB()
nb_model.fit(X_train_scaled, y_train)

MultinomialNB()

In [11]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [12]:
y_pred_nb = nb_model.predict(X_test_scaled)

In [13]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [14]:
print("Naive Bayes Results:")
print(classification_report(y_test, y_pred_nb))

Naive Bayes Results:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       973
           1       0.96      0.94      0.95      1007

    accuracy                           0.95      1980
   macro avg       0.95      0.95      0.95      1980
weighted avg       0.95      0.95      0.95      1980

In [15]:
print("KNN Results:")
print(classification_report(y_test, y_pred_knn))

KNN Results:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       973
           1       0.97      0.99      0.98      1007

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980

In [19]:
import joblib
joblib.dump(nb_model, 'fake_news_nb_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']